In [4]:
import pandas as pd

stockfn_tmp1 = "TEJ Data/stockfn_tmp1.csv"
df = pd.read_csv(stockfn_tmp1)

In [5]:
df

,證券代碼,年月日,開盤價(元),最高價(元),最低價(元),收盤價(元),成交量(千股),成交值(千元),報酬率％,週轉率％,...,現金股利率,股價漲跌(元),高低價差%,次日開盤參考價,次日漲停價,次日跌停價,注意股票(A),處置股票(D),全額交割(Y),市場別
0,1216 統一,20220103,66.0882,66.5685,65.6079,65.7039,4163,286300,-0.2915,0.0733,...,3.9474,-0.2,1.4577,68.4,75.2,61.6,NaN,NaN,NaN,TSE
1,2317 鴻海,20220103,94.7937,95.2473,93.4330,93.4330,22163,2301355,-0.9615,0.1599,...,3.8835,-1.0,1.9231,103.0,113.0,92.7,NaN,NaN,NaN,TSE
2,2330 台積電,20220103,599.5590,612.1510,598.5910,611.1820,73703,46249716,2.6016,0.2842,...,1.6640,16.0,2.2764,631.0,694.0,568.0,NaN,NaN,NaN,TSE
3,2317 鴻海,20220104,94.3402,94.3402,93.4330,93.8866,18460,1912476,0.4854,0.1332,...,3.8647,0.5,0.9709,103.5,113.5,93.2,NaN,NaN,NaN,TSE
4,2330 台積電,20220104,624.7420,635.3970,623.7740,635.3970,90945,59188199,3.9620,0.3507,...,1.6006,25.0,1.9017,656.0,721.0,591.0,NaN,NaN,NaN,TSE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
733,2317 鴻海,20221229,95.3913,95.3913,94.9143,95.1051,38383,3829311,-0.7960,0.2769,...,5.2156,-0.8,0.4975,99.7,109.5,89.8,NaN,NaN,NaN,TSE
734,1216 統一,20221229,65.7000,66.4000,65.7000,66.3000,6697,442736,0.1511,0.1179,...,4.0724,0.1,1.0574,66.3,72.9,59.7,NaN,NaN,NaN,TSE
735,2330 台積電,20221230,450.4420,451.9270,444.0070,444.0070,22297,10079102,0.5605,0.0860,...,2.4526,2.5,1.7937,448.5,493.0,404.0,NaN,NaN,NaN,TSE
736,2317 鴻海,20221230,95.3913,95.8683,95.2005,95.2959,18189,1818159,0.2006,0.1312,...,5.2052,0.2,0.7021,99.9,109.5,90.0,NaN,NaN,NaN,TSE
737,1216 統一,20221230,66.2000,66.9000,66.1000,66.6000,6968,464521,0.4525,0.1226,...,4.0541,0.3,1.2066,66.6,73.2,60.0,NaN,NaN,NaN,TSE

In [6]:
'hello world'.split(' ')

['hello', 'world']

In [7]:
df[['證券代碼', '公司名稱']] = df["證券代碼"].str.split(" ", expand=True)

In [8]:
df

,證券代碼,年月日,開盤價(元),最高價(元),最低價(元),收盤價(元),成交量(千股),成交值(千元),報酬率％,週轉率％,...,股價漲跌(元),高低價差%,次日開盤參考價,次日漲停價,次日跌停價,注意股票(A),處置股票(D),全額交割(Y),市場別,公司名稱
0,1216,20220103,66.0882,66.5685,65.6079,65.7039,4163,286300,-0.2915,0.0733,...,-0.2,1.4577,68.4,75.2,61.6,NaN,NaN,NaN,TSE,統一
1,2317,20220103,94.7937,95.2473,93.4330,93.4330,22163,2301355,-0.9615,0.1599,...,-1.0,1.9231,103.0,113.0,92.7,NaN,NaN,NaN,TSE,鴻海
2,2330,20220103,599.5590,612.1510,598.5910,611.1820,73703,46249716,2.6016,0.2842,...,16.0,2.2764,631.0,694.0,568.0,NaN,NaN,NaN,TSE,台積電
3,2317,20220104,94.3402,94.3402,93.4330,93.8866,18460,1912476,0.4854,0.1332,...,0.5,0.9709,103.5,113.5,93.2,NaN,NaN,NaN,TSE,鴻海
4,2330,20220104,624.7420,635.3970,623.7740,635.3970,90945,59188199,3.9620,0.3507,...,25.0,1.9017,656.0,721.0,591.0,NaN,NaN,NaN,TSE,台積電
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
733,2317,20221229,95.3913,95.3913,94.9143,95.1051,38383,3829311,-0.7960,0.2769,...,-0.8,0.4975,99.7,109.5,89.8,NaN,NaN,NaN,TSE,鴻海
734,1216,20221229,65.7000,66.4000,65.7000,66.3000,6697,442736,0.1511,0.1179,...,0.1,1.0574,66.3,72.9,59.7,NaN,NaN,NaN,TSE,統一
735,2330,20221230,450.4420,451.9270,444.0070,444.0070,22297,10079102,0.5605,0.0860,...,2.5,1.7937,448.5,493.0,404.0,NaN,NaN,NaN,TSE,台積電
736,2317,20221230,95.3913,95.8683,95.2005,95.2959,18189,1818159,0.2006,0.1312,...,0.2,0.7021,99.9,109.5,90.0,NaN,NaN,NaN,TSE,鴻海
737,1216,20221230,66.2000,66.9000,66.1000,66.6000,6968,464521,0.4525,0.1226,...,0.3,1.2066,66.6,73.2,60.0,NaN,NaN,NaN,TSE,統一

In [ ]:
company_name = df["公司名稱"]

df = df.drop(columns=["公司名稱"])

df.insert(loc=2, column="公司名稱", value=company_name)

df

,證券代碼,年月日,公司名稱,開盤價(元),最高價(元),最低價(元),收盤價(元),成交量(千股),成交值(千元),報酬率％,...,現金股利率,股價漲跌(元),高低價差%,次日開盤參考價,次日漲停價,次日跌停價,注意股票(A),處置股票(D),全額交割(Y),市場別
0,1216,20220103,統一,66.0882,66.5685,65.6079,65.7039,4163,286300,-0.2915,...,3.9474,-0.2,1.4577,68.4,75.2,61.6,NaN,NaN,NaN,TSE
1,2317,20220103,鴻海,94.7937,95.2473,93.4330,93.4330,22163,2301355,-0.9615,...,3.8835,-1.0,1.9231,103.0,113.0,92.7,NaN,NaN,NaN,TSE
2,2330,20220103,台積電,599.5590,612.1510,598.5910,611.1820,73703,46249716,2.6016,...,1.6640,16.0,2.2764,631.0,694.0,568.0,NaN,NaN,NaN,TSE
3,2317,20220104,鴻海,94.3402,94.3402,93.4330,93.8866,18460,1912476,0.4854,...,3.8647,0.5,0.9709,103.5,113.5,93.2,NaN,NaN,NaN,TSE
4,2330,20220104,台積電,624.7420,635.3970,623.7740,635.3970,90945,59188199,3.9620,...,1.6006,25.0,1.9017,656.0,721.0,591.0,NaN,NaN,NaN,TSE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,2317,20221212,鴻海,97.2991,97.2991,96.3452,97.2991,19498,1982855,0.0000,...,5.0980,0.0,0.9804,102.0,112.0,91.8,NaN,NaN,NaN,TSE
696,2317,20221213,鴻海,97.2991,97.7761,96.3452,96.3452,34807,3530853,-0.9804,...,5.1485,-1.0,1.4706,101.0,111.0,90.9,NaN,NaN,NaN,TSE
697,2330,20221213,台積電,465.5820,468.5350,463.6130,464.1050,36028,17034191,-0.7368,...,2.3330,-3.5,1.0526,471.5,518.0,424.5,NaN,NaN,NaN,TSE
698,1216,20221213,統一,66.0000,66.2000,65.1000,65.4000,9677,633581,-0.6079,...,4.1284,-0.4,1.6717,65.4,71.9,58.9,NaN,NaN,NaN,TSE
699,2317,20221214,鴻海,96.8222,97.7761,96.3452,97.7761,24772,2530062,1.4851,...,5.0732,1.5,1.4851,102.5,112.5,92.3,NaN,NaN,NaN,TSE

將 pandas 的 Dataframe 存成 csv 檔案

In [10]:
df.to_csv("testsave.csv")